FROM node:lts-alpine
ENV NODE_ENV=production
ENV MONGO_URI=''
ENV PORT=3000
ENV CLIENT_ID_GITHUB=''
ENV CLIENT_SECRET_GITHUB=''
ENV CLIENT_ID_GOOGLE=''
ENV CLIENT_SECRET_GOOGLE=''
ENV CLIENT_ID_DISCORD=''
ENV CLIENT_SECRET_DISCORD=''
WORKDIR /usr/src/app
COPY ["package.json", "package-lock.json*", "npm-shrinkwrap.json*", "./"]
RUN npm install --production --silent && mv node_modules ../
COPY . .
EXPOSE 3000
RUN chown -R node /usr/src/app
USER node
CMD ["npm", "start"]
